### ISSUE TITLE
关于SRC的获奖公示

### ISSUE THREAD

**Issue by wangqr** [zilimengfaker/zilimengfaker#1]
```
无论是本科生还是研究生，在2018年的ACM 学生研究竞赛获奖名单上，都没有见到“Zili Meng"或者”Zili"或者"Meng"的身影。 
```
[上文中的链接](http://conferences.sigcomm.org/sigcomm/2018/src.html)中就有。
![default](https://user-images.githubusercontent.com/8182182/47192945-5d253800-d31e-11e8-9425-a198518675ea.png)

**Comment by zilimengfaker** [comment]
Thanks, replied in "supplymentary material and discussion.md"

**Comment by wangqr** [comment]
You may need to modify README.md accordingly.

**Comment by zilimengfaker** [comment]
modified.
