### ISSUE TITLE
对文章的一些看法

### ISSUE THREAD

**Issue by zx3xyy** [zilimengfaker/zilimengfaker#2]
我认真的读完了整个README.md

先说结论，能看出来作者非常认真地对孟同学的整个申请材料进行了详细研读。文章的中心思想是孟同学的工作其实没那么厉害，不值得评特奖。

我先纠正你的几个错误。

首先你一直提到的SIGCOMM的poster的难度。很多好的工作在正式形成长文之前都会投个poster来“占坑”以及得到一些同行评价。作为网络方向最顶尖的会议，SIGCOMM的poster质量应该还是过得去的。2017年会议的录取率是52/143，应该是30%多。

第二关于你臆测的SIGCOMM SRC的情况完全错误。报名参加SRC的前提是有一作poster或者正文。并不是说交钱就可以参加SRC并且保送一篇poster。因果关系搞反了。

第三是“学生第二作者”的事情。我注意到了你提到了“学生第一作者”的情况，估计你也是明白有些老师会在意自己的署名顺序。那么请你去看一下毕军老师的主页，看一下所有文章的第二作者是不是同一个人，你就能明白孟同学为什么不是“三作”，而是强调“学生第二作者”了。

说实话，我个人认为孟同学的简历和前几届靠科创拿特奖的同学是有差距，但你不能指望每年都有一个clj。看你说话也是圈内人士，应该知道做system出成果的周期要比其他的领域要长很多，很多北美明星phd一年一篇顶会就属于非常牛的了。

孟同学作为一个学生要参评奖学金，提交的材料也没有造假，6篇论文和poster白纸黑字在网上可查，凭什么人家就要被你在网上来回指摘？孟同学的行为顶多算是8分实力，写材料写成了9、10分。可是难道非得谦虚成5分才能在你心目中过关？

最后还是想说一下，无论作者是出于正义感还是其他的什么原因写的这篇文章，你的行文风格实在是令人作呕。满篇文章看似客观讨论，说话留有余地，但是其实字里行间到处对孟同学的明嘲暗讽。我觉得如果要讨论就认认真真的讨论。你要觉得初筛不公平，学校提供了正常渠道反馈的渠道。相反，跑到GitHub上做一个匿名键盘侠，甚至上升人格的攻击显得很low了。

**Comment by zx3xyy** [comment]
另外，邹同学希望你git用的熟练一些，匿名之前把所有身份抹掉
<img width="416" alt="wechatimg102" src="https://user-images.githubusercontent.com/10197320/47193515-4c29f600-d321-11e8-9f52-a22992f9e301.png">

**Comment by wangqr** [comment]
```
孟同学的行为顶多算是8分实力，写材料写成了9、10分。可是难道非得谦虚成5分才能在你心目中过关？
```
这话说不通，正常人思路不是8分实力写8分材料么，为啥不吹就只能写5分呢

**Comment by Trinkle23897** [comment]
似乎是个航院4字班的？

**Comment by ccczzzf** [comment]
> ```
> 孟同学的行为顶多算是8分实力，写材料写成了9、10分。可是难道非得谦虚成5分才能在你心目中过关？
> ```
> 这话说不通，正常人思路不是8分实力写8分材料么，为啥不吹就只能写5分呢

因为他材料里面，在论文那里写的是ACM SIGCOMM 2018，不知是刻意省略了还是漏掉了poster。这是实锤。

**Comment by keavil** [comment]
你好。
首先我也反对对孟同学的明嘲暗讽，哪里说不通就大大方方的说，没必要明里暗里讽刺。

但对于孟同学，我认为他没资格评这个特奖。原因也很简单：在他的PS中，提到：“我的第三篇一作论文也被前述公认排名第一会议 SIGCOMM18（《清华目录》顶尖级会议）录取，我也受 邀赴匈牙利向大会展示自己的成果。” 必须注意到的是，在任何学术引擎中搜索该论文，显示的都是 SIGCOMM Posters and Demos 2018，而该项在分类中区别于SIGCOMM 2018（可以参考dblp：https://dblp.uni-trier.de/search?q=SIGCOMM%202018， 注意右侧的refine by venue）。因此，该行为涉嫌构成学术欺诈。这是不能用”疏忽了“、”漏掉了“来解释的，作为一份PS文章中的每一句话都应该仔细斟酌过。如果今后他的学术论文中也”一时疏忽“，”漏掉了“某个引用，其后果就不是评不了奖学金这么简单的了。

**Comment by reply2xuzou** [comment]
![image](https://user-images.githubusercontent.com/44281618/47194278-9607e180-d30b-11e8-98a6-2254c6d25ff3.png)

请问作者为何在知乎上以 "转载", "原作者" 等字眼回避知乎帐号与github帐号之间的关联?
https://zhuanlan.zhihu.com/p/47132110
![image](https://user-images.githubusercontent.com/44281618/47194308-aae47500-d30b-11e8-92a3-63e98a0e8b5b.png)

![image](https://user-images.githubusercontent.com/44281618/47194391-feef5980-d30b-11e8-9da2-69021d0853be.png)

**Comment by zilimengfaker** [comment]
replied in "supplymentary material and discussion.md"

**Comment by zilimengfaker** [comment]
我把回复也贴在这里一份吧。

1：关于ACM SIGCOMM竞赛的报名和发表demo and poster的先后关系：

此比赛分为几个阶段：
Pre-selection: Students submit their work as a poster/demo here. See eligibility criteria below.
1st round “Poster session”
2nd round “Presentation session”
Announcement of Three Finalists In Each Category (Undergraduate and Graduate)
The Grand Finals:

如果我没有理解错误，那么“获奖”是需要进入第4阶段“Announcement of Three Finalists In Each Category”的，而发表一作demo and poster需要通过第一阶段“Pre-selection”。当然，孟同学在第4阶段中取得了本科生组第一名，是非常不错的成果，但“发表一作SIGCOMM demo and poster"所需要的“通过第一阶段pre selection"的含金量，各位见仁见智吧。和范同学所说的”发表一作poster或正文”应该还是有所区别的。孟同学此poster的全文也在此目录下，长2页，7个引用文献，如果您认为这能代表清华最顶尖的科研水平，那也可以吧。


2：关于孟同学真实实力如何：

这个我不想探讨。一个人的“实力”是看他真正做了什么的，而不是他"有多努力"，在旁人看来多厉害之类。比如我本科就没有发表什么一作A类论文，GPA也远不如孟大神，自认是一个菜鸡，但我也有自知之明，没有去参评特奖。

只是“提交的材料也没有造假”这句有点不妥，孟同学在自我陈述中，写“我的第三篇一作论文也被前述公认排名第一会议 SIGCOMM18（《清华目录》顶尖级会议）录取”， 而SIGCOMM会议的“录取”，是肯定不包含demo and poster的。在dblp,google scholar等，也会特别标注出文献所属会议是"ACM SIGCOMM demo and poster"而不是"ACM SIGCOMM"。

3：关于作者身份的揣摩

关于我是谁，我本来也没打算匿名，算是一个彩蛋吧。凭什么人家这种程度的造假都可以实名还拿出来公示，我给大家提供一点真实信息讨论，反而要匿名？

关于各种对我个人的质疑与人身攻击，我觉得与讨论的主题没有关系。当然，也有很多声音说我“言辞激烈”，“明嘲暗讽”，“令人作呕”的，劝我努力先“提升自己”的。我只想问一句，对于孟同学这种材料，难道不应该去揭露、嘲讽，而是应该跪舔、洗地么？我的良心不允许我这么做。

**Comment by zilimengfaker** [comment]
特意去查了一下此issue作者的cv，果然令人大开眼界。已附在本repo的文件中CV_Chengze_1022.pdf，为范同学10月22日时主页markfan.me上附的cv。

看到最后两行的Publication（也是SIGCOMM/SOSR 的poster and demo不标注)，突然明白了此issue作者的用意。

请范承泽同学好自为之。
