### ISSUE TITLE
关于他有没有分清楚poster和正会的问题

### ISSUE THREAD

**Issue by Diyorazh** [zilimengfaker/zilimengfaker#7]
肯定是分的清楚的呀～ 个人主页有：http://zilimeng.info
附送一份公开简历。

[curriculum-vitae.pdf](https://github.com/zilimengfaker/zilimengfaker/files/2495227/curriculum-vitae.pdf)

**Comment by lizeyan** [comment]
<img width="700" alt="snipaste_2018-10-19_21-23-27" src="https://user-images.githubusercontent.com/12494243/47220770-472e7a80-d3e5-11e8-929a-ebcc9b342ee5.png">
这句话不写清楚是poster都会误解为是长文被录取了。
 @Diyorazh 所提出的只能说明mzl同学本人心里是清楚poster和正会不一样的
。但是他自己既然非常清楚地知道poster和长文的区别，在自己的个人主页也分清楚了，那么在特奖申请这么写，就是在有意混淆视听。
我们不能否认mzl同学其实还是很厉害的事实，也不能忽视他在评选特奖时用的这些伎俩。

**Comment by Diyorazh** [comment]
@lizeyan 不仅你说的这个，还有他的申请表。
我就是单纯觉得，挺优秀的一孩子，真没必要为了申请个奖学金打这种擦边球。
![screen shot 2018-10-19 at 5 16 16 pm](https://user-images.githubusercontent.com/34129418/47225257-3cc5ae00-d3f0-11e8-9bb1-c62dee3daf48.png)

以及大家可以注意一下，不仅是SIGCOMM, SOSR也没有写是poster。

**Comment by zaxguo** [comment]
。。。。这种人我一般会认为integrity有问题

**Comment by ztz1989** [comment]
个人觉得没必要纠结，因为sigcomm所有的东西都很容易核实，评审不会那么容易被误导的。而且有的时候google scholar上面生成的有些会议的文章也没有分正会或者poster/demo,点进去一看就知道是什么，所以就目前这些材料很难让我觉得这个同学有问题～
