### ISSUE TITLE
请repo owner在readme中更醒目地指出其他人的讨论内容的位置

### ISSUE THREAD

**Issue by duanqn** [zilimengfaker/zilimengfaker#9]
目前好像写在了最后一行，大部分人点进来也就看一下readme，而readme的内容并没有根据后续讨论进行修正。

**Comment by zilimengfaker** [comment]
与正文相关的部分（如发表poster需要通过一个pre selection，Zili Meng同学确实获得了本科生组的第一名）等已经在原文中修正了。

其他与正文无关的讨论（如Meng同学真实实力如何，此文作者是谁（其实也可以说是共同作者之一）之类，不是此文的重点，放在discussion里。

**Comment by zilimengfaker** [comment]
已经在readme.md后面附了一份
